fix: cei pattern in CollateralJoin
defi-wonderland/hai-core pull request #13
Opened 2023-10-18 18:00 UTC by 0xJabberwock

[HAI-316](https://linear.app/defi-wonderland/issue/HAI-316)

2023-10-18 23:30 UTC, xBA5ED requested changes

2023-10-18 23:30 UTC, xBA5ED commented on src/contracts/utils/CollateralJoin.sol
> +    collateral.safeTransferFrom(msg.sender, address(this), _wei);
Safety concern, a malicious user can `join` >  reenter with ERC777 > `exit`. Then they have free tokens :eyes: 

I would leave this `safeTransferFrom(..)` at the top as it functions as a check

2023-10-24 14:51 UTC, xBA5ED approved these changes
:ship:

2023-10-27 11:20 UTC, wei3erHase approved these changes
🚀

2023-10-27 11:20 UTC, merged