feat: `DelayedOracle` store invalid feed
defi-wonderland/hai-core pull request #2
Opened 2023-10-17 22:43 UTC by 0xJabberwock

2023-10-20 04:00 UTC, 0xJabberwock reviewed
Code comments are much appreciated! ✅

2023-10-23 15:49 UTC, wei3erHase commented on src/contracts/oracles/DelayedOracle.sol
> +        (uint256 _priceFeedValue, bool _hasValidValue) = _getPriceSourceResult();
hmmm feels weird that there are 2 different lines (65 and 78) that do the same, please refactor this logic 🙏

2023-10-23 15:49 UTC, wei3erHase requested changes
please simplify logic 🙏

2023-10-24 15:16 UTC, xBA5ED commented on src/contracts/oracles/DelayedOracle.sol
> +        (uint256 _priceFeedValue, bool _hasValidValue) = _getPriceSourceResult();
True, it was done to save some gas by not doing the `_getPriceSourceResult()` call in the case that the revert case was hit. I'll make it so the call is done beforehand

2023-10-30 13:34 UTC, wei3erHase commented on src/contracts/oracles/DelayedOracle.sol
> +        return _hasValidValue;
hmmmmmmmmmmm
i think we need to update the `lastUpdateTime`
the feed must be available 1hr (or delay time) after the valid feed was fetched (not after the 1st invalid one)

2023-10-30 13:35 UTC, wei3erHase requested changes
please update the `lastUpdateTime` also when re-fetching an invalid feed 🙏

2023-11-02 12:20 UTC, wei3erHase commented on src/contracts/oracles/DelayedOracle.sol
> +      _nextFeed = Feed(_priceFeedValue, _hasValidValue);
GREAT catch.

2023-11-02 12:22 UTC, wei3erHase commented on src/contracts/oracles/DelayedOracle.sol
> +    return _delayHasElapsed() || !_nextFeed.isValid;
love you pal 😍

2023-11-02 12:22 UTC, wei3erHase approved these changes
chapeau! 🎩

2023-11-02 12:23 UTC, merged